name: CD-dispatch.yml
on:
  workflow_dispatch:
    inputs:
      build_secret:
        type: string
        description: Build secret

jobs:
  check-user-permissions:
    runs-on: ubuntu-22.04
    steps:
      - name: Check user permission
        uses: stjude/proteinpaint/.github/actions/check-user-permissions@master
        with:
          BUILD_SECRET: ${{ secrets.BUILD_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_BUILD_SECRET: ${{ github.event.inputs.build_secret }}

  build:
    needs: check-user-permissions
    runs-on: ubuntu-22.04
    steps:
      - name: Run deploy action
        uses: peter-evans/repository-dispatch@v2
        if: ${{ !startsWith(github.ref_name, 'release') && !startsWith(github.ref_name, 'prerelease') }}
        with:
          token: ${{ secrets.PAT }}
          repository: stjude/sj-pp
          event-type: test
          client-payload: 'Test'