name: Rust Build

on:
  workflow_dispatch:
    inputs:
      build_secret:
        type: string
        description: Build secret

jobs:
  check-user-permissions:
      runs-on: ubuntu-22.04
      steps:
        - name: Check user permission
          uses: stjude/proteinpaint/.github/actions/check-user-permissions@master
          with:
            BUILD_SECRET: ${{ secrets.BUILD_SECRET }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INPUT_BUILD_SECRET: ${{ github.event.inputs.build_secret }}

  build:
    needs: check-user-permissions
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/stjude/rust_debian_testing:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build rust
        run: |
          rustup default 1.86.0
          cd rust && cargo build --release
          ./extract_binaries.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-binaries
          path: rust/extracted_binaries